package com.odm.oa.mapper;

import com.odm.oa.entity.AddressPrivate;
import java.util.List;

public interface AddressPrivateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_private
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_private
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    int insert(AddressPrivate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_private
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    AddressPrivate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_private
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    List<AddressPrivate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_private
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    int updateByPrimaryKey(AddressPrivate record);
}