package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.ApprovalProcess;

public interface ApprovalProcessMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table approval_process
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table approval_process
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(ApprovalProcess record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table approval_process
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	ApprovalProcess selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table approval_process
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<ApprovalProcess> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table approval_process
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(ApprovalProcess record);
}