package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.Area;
import com.odm.oa.model.request.AreaPagination;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    Area selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    List<Area> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    int updateByPrimaryKey(Area record);
    List<Area> areaList(AreaPagination areaPagination) ;
}