package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.AttendanceRecord;
import com.odm.oa.model.request.PaginationBase;

public interface AttendanceRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance_record
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance_record
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int insert(AttendanceRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance_record
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	AttendanceRecord selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance_record
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	List<AttendanceRecord> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance_record
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int updateByPrimaryKey(AttendanceRecord record);

	/**
     * 分页查询
     * @param request
     * @return
     */
	List<AttendanceRecord> pageList(PaginationBase request);
}