package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.Department;
import com.odm.oa.entity.ex.DepartmentEx;
import com.odm.oa.model.request.DepartmentPagination;

public interface DepartmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	Department selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<Department> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(Department record);

	List<DepartmentEx> pagination(DepartmentPagination request);
	Department selectByName(String name);
	Department selectByManagerId(Long managerId);
	Department selectByAssistantManagerId(Long assistantManagerId);
}