package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.Dictionary;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    Dictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    List<Dictionary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    int updateByPrimaryKey(Dictionary record);
    List<Dictionary> selectByCodeType(String codeType);
}