package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.File;
import com.odm.oa.entity.ResponseFile;

import javax.xml.ws.Response;

public interface FileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(File record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	File selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<File> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(File record);
	File selectByUrl(String url);
	List<ResponseFile> getFileByNotice(Long id);
}