package com.odm.oa.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.odm.oa.entity.ForgetToClockOutApply;
import com.odm.oa.model.request.PaginationBase;

public interface ForgetToClockOutApplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forget_to_clock_out_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forget_to_clock_out_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int insert(ForgetToClockOutApply record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forget_to_clock_out_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	ForgetToClockOutApply selectByPrimaryKey(Long id);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forget_to_clock_out_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	List<ForgetToClockOutApply> selectAll();


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forget_to_clock_out_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int updateByPrimaryKey(ForgetToClockOutApply record);


	/**
     * 分页查询
     * @param request
     * @return
     */
	List<ForgetToClockOutApply> pageList(PaginationBase request);


	ForgetToClockOutApply selectIsForget(@Param("staffno") String staffno, @Param("myDate")Date myDate);
}