package com.odm.oa.mapper;

import com.odm.oa.entity.Goods;
import com.odm.oa.entity.ex.GoodsExxg;

import java.util.List;

public interface GoodsMapperxg {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Apr 26 10:04:16 CST 2018
     */
    int deleteByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Apr 26 10:04:16 CST 2018
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Apr 26 10:04:16 CST 2018
     */
    Goods selectByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Apr 26 10:04:16 CST 2018
     */
    List<Goods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Apr 26 10:04:16 CST 2018
     */
    int updateByPrimaryKey(Goods record);
    
    List<Goods>  selectAllByConditionxg(Goods record);
    
    List<GoodsExxg>  selectAllByConditionsxg(GoodsExxg record);
    Long selectMaxStaffNoxg();
}