package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.Department;
import com.odm.oa.entity.Goods;
import com.odm.oa.entity.Position;
import com.odm.oa.entity.SystemRole;
import com.odm.oa.entity.ex.DepartmentEx;
import com.odm.oa.entity.ex.GoodsEx_WJ;
import com.odm.oa.entity.ex.SystemRoleEx;
import com.odm.oa.model.request.DepartmentPagination;
import com.odm.oa.model.request.GoodsPagination_WJ;
import com.odm.oa.model.request.PaginationBase;
import com.odm.oa.model.request.SystemRolePagination;

public interface GoodsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table goods
	 *
	 * @mbg.generated Thu Apr 26 10:04:16 CST 2018
	 */
	int deleteByPrimaryKey(Long goodsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table goods
	 *
	 * @mbg.generated Thu Apr 26 10:04:16 CST 2018
	 */
	int insert(Goods record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table goods
	 *
	 * @mbg.generated Thu Apr 26 10:04:16 CST 2018
	 */
	int updateByPrimaryKey(Goods record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table goods
	 *
	 * @mbg.generated Thu Apr 26 10:04:16 CST 2018
	 */
	
	Goods selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table goods
	 *
	 * @mbg.generated Thu Apr 26 10:04:16 CST 2018
	 */
	List<Goods> selectAll();
	List<GoodsEx_WJ> pagination(GoodsPagination_WJ request);
	List<GoodsEx_WJ> selectRoleList(GoodsPagination_WJ goodsPagination);
	List<GoodsEx_WJ>  selectAllByConditions(GoodsPagination_WJ request);
	Goods selectByName(String name);
	int getByName(String name);
}