package com.odm.oa.mapper;

import com.odm.oa.entity.IllegalWord;
import com.odm.oa.entity.ex.IllegalWordEx;
import com.odm.oa.model.request.IllegalWordPagination;

import java.util.List;
import java.util.Set;

public interface IllegalWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table illegal_word
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table illegal_word
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    int insert(IllegalWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table illegal_word
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    IllegalWord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table illegal_word
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    List<IllegalWord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table illegal_word
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    int updateByPrimaryKey(IllegalWord record);
    List<IllegalWordEx> pagination(IllegalWordPagination request);
    IllegalWord selectByWord(String word);
    Set<String> listIllegalWord();
}