package com.odm.oa.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.odm.oa.entity.Leaves;

public interface LeavesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leaves
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leaves
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int insert(Leaves record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leaves
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	Leaves selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leaves
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	List<Leaves> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leaves
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int updateByPrimaryKey(Leaves record);

	Leaves selectIsLeaveType(@Param("staffno") String staffno, @Param("myDate")Date myDate);
}