package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.LeaveType;
import com.odm.oa.model.request.PaginationBase;

public interface LeaveTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leave_type
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leave_type
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int insert(LeaveType record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leave_type
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	LeaveType selectByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leave_type
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	List<LeaveType> selectAll();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table leave_type
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int updateByPrimaryKey(LeaveType record);
	/**
     * 分页查询
     * @param request
     * @return
     */
    List<LeaveType> pageList(PaginationBase request);
    /**
     * 根据名称查询
     * @param name
     * @return
     */
    int getByName(String name);
}