package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.LegalHoliday;

public interface LegalHolidayMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table legal_holiday
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table legal_holiday
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(LegalHoliday record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table legal_holiday
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	LegalHoliday selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table legal_holiday
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<LegalHoliday> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table legal_holiday
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(LegalHoliday record);
}