package com.odm.oa.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.odm.oa.entity.LegworkApply;

public interface LegworkApplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table legwork_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table legwork_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int insert(LegworkApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table legwork_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	LegworkApply selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table legwork_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	List<LegworkApply> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table legwork_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int updateByPrimaryKey(LegworkApply record);

	LegworkApply selectLegworkApply(@Param("staffno") String staffno, @Param("myDate")Date myDate);
}