package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.Message;
import com.odm.oa.entity.ex.MessageEx;
import com.odm.oa.model.request.MessagePagination;

public interface MessageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	Message selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<Message> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(Message record);
	List<MessageEx> pagination(MessagePagination request);
	List<Message> selectBySendIdAndReceiveId(MessageEx request);
}