package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.NoticeResponse;
import com.odm.oa.entity.Staff;
import com.odm.oa.entity.ex.ResponseEx;
import com.odm.oa.model.request.NoticeResponsePagination;

public interface NoticeResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_response
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_response
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    int insert(NoticeResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_response
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    NoticeResponse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_response
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    List<NoticeResponse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_response
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    int updateByPrimaryKey(NoticeResponse record);
    List<ResponseEx> pagination(NoticeResponsePagination request);
}