package com.odm.oa.mapper;

import com.odm.oa.entity.NoticeType;
import com.odm.oa.model.request.PaginationBase;

import java.util.List;

public interface NoticeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_type
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_type
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    int insert(NoticeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_type
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    NoticeType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_type
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    List<NoticeType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_type
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    int updateByPrimaryKey(NoticeType record);
    List<NoticeType> pageList(PaginationBase p);
    int getByName(String name);
    List<NoticeType> selectList();
}