package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.Notice;
import com.odm.oa.entity.ex.NoticeEx;
import com.odm.oa.model.request.NoticePagination;
import com.odm.oa.model.request.SubmitNoticeRequest;

public interface NoticeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notice
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notice
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(Notice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notice
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	Notice selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notice
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<Notice> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notice
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(Notice record);
	List<NoticeEx> pagination(NoticePagination request);
	NoticeEx lookOneNotice(Long id);
	List<NoticeEx> getPersonalNotice(String no);
	List<NoticeEx> getSavedNotice(String no);
	List<NoticeEx> getReleasedNotice(String no);
	List<NoticeEx> getToReviewNotice(String no);
	SubmitNoticeRequest getEditData(Long id);
	Long[] getEditDataStaff(Long id);
	Long getPieChartCount(String staffNo,Long typeId);
	void deleteById(Long id);
}