package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.NoticeRecord;
import com.odm.oa.model.request.NoticeDetialRequest;

public interface NoticeRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notice_record
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notice_record
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(NoticeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notice_record
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	NoticeRecord selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notice_record
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<NoticeRecord> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notice_record
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(NoticeRecord record);
	NoticeRecord selectByNoticeIdStaffNo(NoticeDetialRequest request);
	List<NoticeRecord> selectByNoticeId(Long noticeId);
}