package com.odm.oa.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.odm.oa.entity.OnBusinessApply;

public interface OnBusinessApplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table on_business_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table on_business_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int insert(OnBusinessApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table on_business_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	OnBusinessApply selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table on_business_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	List<OnBusinessApply> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table on_business_apply
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	int updateByPrimaryKey(OnBusinessApply record);

	OnBusinessApply selectIsOnBusiness(@Param("staffno") String staffno, @Param("myDate")Date myDate);
}