package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.Position;
import com.odm.oa.entity.ex.PositionEx;
import com.odm.oa.model.request.PaginationBase;

public interface PositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Tue Feb 27 10:37:25 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Tue Feb 27 10:37:25 CST 2018
     */
    int insert(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Tue Feb 27 10:37:25 CST 2018
     */
    Position selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Tue Feb 27 10:37:25 CST 2018
     */
    List<Position> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Tue Feb 27 10:37:25 CST 2018
     */
    int updateByPrimaryKey(Position record);
    List<Position> pageList(PaginationBase p);
    int getByName(String name);
}