package com.odm.oa.mapper;

import java.util.List;
import com.odm.oa.entity.Project;
import com.odm.oa.entity.ex.ProjectEx;
import com.odm.oa.model.request.ProjectPagination;

public interface ProjectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(Project record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	Project selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<Project> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(Project record);
	List<ProjectEx> pagination(ProjectPagination request);
	Project selectByName(String name);
	Project selectByManagerId(Long managerId);
	Project selectByAssistantManagerId(Long assistantManagerId);
}