package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.Staff;
import com.odm.oa.entity.ex.StaffEx;
import com.odm.oa.model.request.StaffPagination;

public interface StaffMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	Staff selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<Staff> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(Staff record);

	Staff selectStaffByStaffNo(Staff staff);
	
	List<StaffEx> pagination(StaffPagination request);
	List<StaffEx> paginationPublic(StaffPagination request);
	List<StaffEx> paginationPrivate(StaffPagination request);
	
	List<String> selectPrivilegeByUsrId(String userId);
	
	List<StaffEx> selectStaffInfo(StaffPagination request);
	StaffEx selectStaffByPrimaryKey(long staffId);
	StaffEx selectExByPrimaryKey(Long id);
	List<StaffEx> selectExByPositionId(Long positionId);
	List<StaffEx> selectStaffsByDepartmentId(Long departmentId);
	Staff selectByMobilePhone(String mobilePhone);
	String selectMaxStaffNo();
	List<StaffEx> selectStaffByQuery(StaffEx request);
	List<Staff> listAuthor();
	List<Staff> listIllegalWordPerson();
	List<Staff> listReviewPerson();
	Long getIdByStaffNo(String no);
}