package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.SystemAccountOperationLog;

public interface SystemAccountOperationLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_account_operation_log
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_account_operation_log
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(SystemAccountOperationLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_account_operation_log
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	SystemAccountOperationLog selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_account_operation_log
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<SystemAccountOperationLog> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_account_operation_log
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(SystemAccountOperationLog record);
}