package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.SystemRole;
import com.odm.oa.entity.ex.SystemRoleEx;
import com.odm.oa.model.request.SystemRolePagination;

public interface SystemRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_role
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_role
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(SystemRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_role
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	SystemRole selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_role
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<SystemRole> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_role
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(SystemRole record);
	
    int updateRoleByPrimaryKey(SystemRoleEx param);
	
    SystemRole selectRoleDetailByPrimaryKey(Long id);
	
	List<SystemRoleEx> selectRoleList(SystemRolePagination systemRolePagination);
	
	int deleteList(List<String> param);
	
	/** 
	 * 通过角色类型查询角色表
	 * 一般情况下是一个对象
	 * 防止出问题，先用list装，然后取第一个对象就可以了
	 * @param roleType
	 * @return
	 */
	List<SystemRoleEx> selectRoleDetailByRoleType(Long roleType);
}