package com.odm.oa.mapper;

import java.util.List;

import com.odm.oa.entity.SystemUserRole;

public interface SystemUserRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_user_role
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_user_role
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int insert(SystemUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_user_role
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	SystemUserRole selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_user_role
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	List<SystemUserRole> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_user_role
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	int updateByPrimaryKey(SystemUserRole record);
	
	int updateByRoleId(SystemUserRole record);
	int insertUserRole(SystemUserRole record);

	List<SystemUserRole> selectAllByRoleId(long roleId);
	
	SystemUserRole selectAllByStaffId(long staffId);
}