package com.odm.oa.entity;

import java.util.Date;

public class AddressPrivate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_private.id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_private.staff_no
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    private String staffNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_private.staff_id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    private Long staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_private.del_flg
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    private Boolean delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_private.version
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_private.create_id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_private.create_time
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_private.update_id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_private.update_time
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_private.id
     *
     * @return the value of address_private.id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_private.id
     *
     * @param id the value for address_private.id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_private.staff_no
     *
     * @return the value of address_private.staff_no
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public String getStaffNo() {
        return staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_private.staff_no
     *
     * @param staffNo the value for address_private.staff_no
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo == null ? null : staffNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_private.staff_id
     *
     * @return the value of address_private.staff_id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public Long getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_private.staff_id
     *
     * @param staffId the value for address_private.staff_id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_private.del_flg
     *
     * @return the value of address_private.del_flg
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_private.del_flg
     *
     * @param delFlg the value for address_private.del_flg
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_private.version
     *
     * @return the value of address_private.version
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_private.version
     *
     * @param version the value for address_private.version
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_private.create_id
     *
     * @return the value of address_private.create_id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_private.create_id
     *
     * @param createId the value for address_private.create_id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_private.create_time
     *
     * @return the value of address_private.create_time
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_private.create_time
     *
     * @param createTime the value for address_private.create_time
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_private.update_id
     *
     * @return the value of address_private.update_id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_private.update_id
     *
     * @param updateId the value for address_private.update_id
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_private.update_time
     *
     * @return the value of address_private.update_time
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_private.update_time
     *
     * @param updateTime the value for address_private.update_time
     *
     * @mbg.generated Tue Mar 27 15:24:07 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}