package com.odm.oa.entity;

import java.util.Date;

public class ApprovalProcess {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.ID
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.PERSON_ID
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String personId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.APPROVAL
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long approval;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.APPROVE_ID
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long approveId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.APPROVAL_FLG
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Boolean approvalFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.OPINION
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String opinion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Boolean delFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column approval_process.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.ID
	 * @return  the value of approval_process.ID
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.ID
	 * @param id  the value for approval_process.ID
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.PERSON_ID
	 * @return  the value of approval_process.PERSON_ID
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getPersonId() {
		return personId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.PERSON_ID
	 * @param personId  the value for approval_process.PERSON_ID
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setPersonId(String personId) {
		this.personId = personId == null ? null : personId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.APPROVAL
	 * @return  the value of approval_process.APPROVAL
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getApproval() {
		return approval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.APPROVAL
	 * @param approval  the value for approval_process.APPROVAL
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setApproval(Long approval) {
		this.approval = approval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.APPROVE_ID
	 * @return  the value of approval_process.APPROVE_ID
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getApproveId() {
		return approveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.APPROVE_ID
	 * @param approveId  the value for approval_process.APPROVE_ID
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setApproveId(Long approveId) {
		this.approveId = approveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.APPROVAL_FLG
	 * @return  the value of approval_process.APPROVAL_FLG
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Boolean getApprovalFlg() {
		return approvalFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.APPROVAL_FLG
	 * @param approvalFlg  the value for approval_process.APPROVAL_FLG
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setApprovalFlg(Boolean approvalFlg) {
		this.approvalFlg = approvalFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.OPINION
	 * @return  the value of approval_process.OPINION
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getOpinion() {
		return opinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.OPINION
	 * @param opinion  the value for approval_process.OPINION
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setOpinion(String opinion) {
		this.opinion = opinion == null ? null : opinion.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.del_flg
	 * @return  the value of approval_process.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Boolean getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.del_flg
	 * @param delFlg  the value for approval_process.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setDelFlg(Boolean delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.version
	 * @return  the value of approval_process.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.version
	 * @param version  the value for approval_process.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.create_id
	 * @return  the value of approval_process.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.create_id
	 * @param createId  the value for approval_process.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.create_time
	 * @return  the value of approval_process.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.create_time
	 * @param createTime  the value for approval_process.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.update_id
	 * @return  the value of approval_process.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.update_id
	 * @param updateId  the value for approval_process.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column approval_process.update_time
	 * @return  the value of approval_process.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column approval_process.update_time
	 * @param updateTime  the value for approval_process.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}