package com.odm.oa.entity;

import java.util.Date;

public class Area {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_kbn
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    private String areaKbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_name
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.follow_area_id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    private Long followAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.del_flg
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    private Boolean delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.version
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.create_id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.create_time
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.update_id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.update_time
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_kbn
     *
     * @return the value of area.area_kbn
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public String getAreaKbn() {
        return areaKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_kbn
     *
     * @param areaKbn the value for area.area_kbn
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public void setAreaKbn(String areaKbn) {
        this.areaKbn = areaKbn == null ? null : areaKbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_name
     *
     * @return the value of area.area_name
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_name
     *
     * @param areaName the value for area.area_name
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.follow_area_id
     *
     * @return the value of area.follow_area_id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public Long getFollowAreaId() {
        return followAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.follow_area_id
     *
     * @param followAreaId the value for area.follow_area_id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public void setFollowAreaId(Long followAreaId) {
        this.followAreaId = followAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.del_flg
     *
     * @return the value of area.del_flg
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.del_flg
     *
     * @param delFlg the value for area.del_flg
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.version
     *
     * @return the value of area.version
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.version
     *
     * @param version the value for area.version
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.create_id
     *
     * @return the value of area.create_id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.create_id
     *
     * @param createId the value for area.create_id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.create_time
     *
     * @return the value of area.create_time
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.create_time
     *
     * @param createTime the value for area.create_time
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.update_id
     *
     * @return the value of area.update_id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.update_id
     *
     * @param updateId the value for area.update_id
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.update_time
     *
     * @return the value of area.update_time
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.update_time
     *
     * @param updateTime the value for area.update_time
     *
     * @mbg.generated Tue Feb 27 17:04:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}