package com.odm.oa.entity;

import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.odm.oa.utils.CustomJsonDateDeserializer;

public class AttendanceRecordExcelImport {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.staffNo
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String staffno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.cardName
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String cardname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.name
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.departmentId
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String departmentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.site
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String site;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.state
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.detection
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String detection;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.del_flg
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Boolean delFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.version
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.create_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.create_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.update_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record_excel_import.update_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.id
	 * @return  the value of attendance_record_excel_import.id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.id
	 * @param id  the value for attendance_record_excel_import.id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.staffNo
	 * @return  the value of attendance_record_excel_import.staffNo
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getStaffno() {
		return staffno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.staffNo
	 * @param staffno  the value for attendance_record_excel_import.staffNo
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setStaffno(String staffno) {
		this.staffno = staffno == null ? null : staffno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.cardName
	 * @return  the value of attendance_record_excel_import.cardName
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getCardname() {
		return cardname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.cardName
	 * @param cardname  the value for attendance_record_excel_import.cardName
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setCardname(String cardname) {
		this.cardname = cardname == null ? null : cardname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.name
	 * @return  the value of attendance_record_excel_import.name
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.name
	 * @param name  the value for attendance_record_excel_import.name
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.departmentId
	 * @return  the value of attendance_record_excel_import.departmentId
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getDepartmentid() {
		return departmentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.departmentId
	 * @param departmentid  the value for attendance_record_excel_import.departmentId
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setDepartmentid(String departmentid) {
		this.departmentid = departmentid == null ? null : departmentid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.time
	 * @return  the value of attendance_record_excel_import.time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.time
	 * @param time  the value for attendance_record_excel_import.time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	@JsonDeserialize(using = CustomJsonDateDeserializer.class)
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.site
	 * @return  the value of attendance_record_excel_import.site
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getSite() {
		return site;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.site
	 * @param site  the value for attendance_record_excel_import.site
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setSite(String site) {
		this.site = site == null ? null : site.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.state
	 * @return  the value of attendance_record_excel_import.state
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.state
	 * @param state  the value for attendance_record_excel_import.state
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.detection
	 * @return  the value of attendance_record_excel_import.detection
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getDetection() {
		return detection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.detection
	 * @param detection  the value for attendance_record_excel_import.detection
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setDetection(String detection) {
		this.detection = detection == null ? null : detection.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.del_flg
	 * @return  the value of attendance_record_excel_import.del_flg
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Boolean getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.del_flg
	 * @param delFlg  the value for attendance_record_excel_import.del_flg
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setDelFlg(Boolean delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.version
	 * @return  the value of attendance_record_excel_import.version
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.version
	 * @param version  the value for attendance_record_excel_import.version
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.create_id
	 * @return  the value of attendance_record_excel_import.create_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.create_id
	 * @param createId  the value for attendance_record_excel_import.create_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.create_time
	 * @return  the value of attendance_record_excel_import.create_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.create_time
	 * @param createTime  the value for attendance_record_excel_import.create_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.update_id
	 * @return  the value of attendance_record_excel_import.update_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.update_id
	 * @param updateId  the value for attendance_record_excel_import.update_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record_excel_import.update_time
	 * @return  the value of attendance_record_excel_import.update_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record_excel_import.update_time
	 * @param updateTime  the value for attendance_record_excel_import.update_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}