package com.odm.oa.entity;

import java.util.Date;

public class AttendanceRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.PERSON_ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String personId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.ATTENDANCE_DATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date attendanceDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.WORKTIME
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date worktime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.CLOSINGTIME
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date closingtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.ISWORK
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Boolean iswork;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.LEAVE_TYPE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Long leaveType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.LATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Boolean late;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.LEAVE_EARLY
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Boolean leaveEarly;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.ABSENTEEISM
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Boolean absenteeism;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.ON_BUSINESS
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Long onBusiness;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.FORGET_TO_CLOCK_OUT
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Long forgetToClockOut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.LEGWORK
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Long legwork;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.del_flg
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Boolean delFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.version
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.create_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.create_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.update_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_record.update_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.ID
	 * @return  the value of attendance_record.ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.ID
	 * @param id  the value for attendance_record.ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.PERSON_ID
	 * @return  the value of attendance_record.PERSON_ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getPersonId() {
		return personId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.PERSON_ID
	 * @param personId  the value for attendance_record.PERSON_ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setPersonId(String personId) {
		this.personId = personId == null ? null : personId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.ATTENDANCE_DATE
	 * @return  the value of attendance_record.ATTENDANCE_DATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getAttendanceDate() {
		return attendanceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.ATTENDANCE_DATE
	 * @param attendanceDate  the value for attendance_record.ATTENDANCE_DATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setAttendanceDate(Date attendanceDate) {
		this.attendanceDate = attendanceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.WORKTIME
	 * @return  the value of attendance_record.WORKTIME
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getWorktime() {
		return worktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.WORKTIME
	 * @param worktime  the value for attendance_record.WORKTIME
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setWorktime(Date worktime) {
		this.worktime = worktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.CLOSINGTIME
	 * @return  the value of attendance_record.CLOSINGTIME
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getClosingtime() {
		return closingtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.CLOSINGTIME
	 * @param closingtime  the value for attendance_record.CLOSINGTIME
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setClosingtime(Date closingtime) {
		this.closingtime = closingtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.ISWORK
	 * @return  the value of attendance_record.ISWORK
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Boolean getIswork() {
		return iswork;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.ISWORK
	 * @param iswork  the value for attendance_record.ISWORK
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setIswork(Boolean iswork) {
		this.iswork = iswork;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.LEAVE_TYPE
	 * @return  the value of attendance_record.LEAVE_TYPE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Long getLeaveType() {
		return leaveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.LEAVE_TYPE
	 * @param leaveType  the value for attendance_record.LEAVE_TYPE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setLeaveType(Long leaveType) {
		this.leaveType = leaveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.LATE
	 * @return  the value of attendance_record.LATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Boolean getLate() {
		return late;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.LATE
	 * @param late  the value for attendance_record.LATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setLate(Boolean late) {
		this.late = late;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.LEAVE_EARLY
	 * @return  the value of attendance_record.LEAVE_EARLY
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Boolean getLeaveEarly() {
		return leaveEarly;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.LEAVE_EARLY
	 * @param leaveEarly  the value for attendance_record.LEAVE_EARLY
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setLeaveEarly(Boolean leaveEarly) {
		this.leaveEarly = leaveEarly;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.ABSENTEEISM
	 * @return  the value of attendance_record.ABSENTEEISM
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Boolean getAbsenteeism() {
		return absenteeism;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.ABSENTEEISM
	 * @param absenteeism  the value for attendance_record.ABSENTEEISM
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setAbsenteeism(Boolean absenteeism) {
		this.absenteeism = absenteeism;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.ON_BUSINESS
	 * @return  the value of attendance_record.ON_BUSINESS
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Long getOnBusiness() {
		return onBusiness;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.ON_BUSINESS
	 * @param onBusiness  the value for attendance_record.ON_BUSINESS
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setOnBusiness(Long onBusiness) {
		this.onBusiness = onBusiness;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.FORGET_TO_CLOCK_OUT
	 * @return  the value of attendance_record.FORGET_TO_CLOCK_OUT
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Long getForgetToClockOut() {
		return forgetToClockOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.FORGET_TO_CLOCK_OUT
	 * @param forgetToClockOut  the value for attendance_record.FORGET_TO_CLOCK_OUT
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setForgetToClockOut(Long forgetToClockOut) {
		this.forgetToClockOut = forgetToClockOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.LEGWORK
	 * @return  the value of attendance_record.LEGWORK
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Long getLegwork() {
		return legwork;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.LEGWORK
	 * @param legwork  the value for attendance_record.LEGWORK
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setLegwork(Long legwork) {
		this.legwork = legwork;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.del_flg
	 * @return  the value of attendance_record.del_flg
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Boolean getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.del_flg
	 * @param delFlg  the value for attendance_record.del_flg
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setDelFlg(Boolean delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.version
	 * @return  the value of attendance_record.version
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.version
	 * @param version  the value for attendance_record.version
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.create_id
	 * @return  the value of attendance_record.create_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.create_id
	 * @param createId  the value for attendance_record.create_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.create_time
	 * @return  the value of attendance_record.create_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.create_time
	 * @param createTime  the value for attendance_record.create_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.update_id
	 * @return  the value of attendance_record.update_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.update_id
	 * @param updateId  the value for attendance_record.update_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_record.update_time
	 * @return  the value of attendance_record.update_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_record.update_time
	 * @param updateTime  the value for attendance_record.update_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}