package com.odm.oa.entity;

import java.util.Date;

public class Dictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.id
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.CODE_TYPE
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private String codeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.code_key
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private String codeKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.value
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.CODE_DESC
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private String codeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.VALID_FLAG
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private String validFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.ORDER_ID
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.del_flg
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private Boolean delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.version
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.create_id
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.create_time
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.update_id
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.update_time
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.id
     *
     * @return the value of dictionary.id
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.id
     *
     * @param id the value for dictionary.id
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.CODE_TYPE
     *
     * @return the value of dictionary.CODE_TYPE
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.CODE_TYPE
     *
     * @param codeType the value for dictionary.CODE_TYPE
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.code_key
     *
     * @return the value of dictionary.code_key
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public String getCodeKey() {
        return codeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.code_key
     *
     * @param codeKey the value for dictionary.code_key
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setCodeKey(String codeKey) {
        this.codeKey = codeKey == null ? null : codeKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.value
     *
     * @return the value of dictionary.value
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.value
     *
     * @param value the value for dictionary.value
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.CODE_DESC
     *
     * @return the value of dictionary.CODE_DESC
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public String getCodeDesc() {
        return codeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.CODE_DESC
     *
     * @param codeDesc the value for dictionary.CODE_DESC
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setCodeDesc(String codeDesc) {
        this.codeDesc = codeDesc == null ? null : codeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.VALID_FLAG
     *
     * @return the value of dictionary.VALID_FLAG
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public String getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.VALID_FLAG
     *
     * @param validFlag the value for dictionary.VALID_FLAG
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setValidFlag(String validFlag) {
        this.validFlag = validFlag == null ? null : validFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.ORDER_ID
     *
     * @return the value of dictionary.ORDER_ID
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.ORDER_ID
     *
     * @param orderId the value for dictionary.ORDER_ID
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.del_flg
     *
     * @return the value of dictionary.del_flg
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.del_flg
     *
     * @param delFlg the value for dictionary.del_flg
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.version
     *
     * @return the value of dictionary.version
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.version
     *
     * @param version the value for dictionary.version
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.create_id
     *
     * @return the value of dictionary.create_id
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.create_id
     *
     * @param createId the value for dictionary.create_id
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.create_time
     *
     * @return the value of dictionary.create_time
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.create_time
     *
     * @param createTime the value for dictionary.create_time
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.update_id
     *
     * @return the value of dictionary.update_id
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.update_id
     *
     * @param updateId the value for dictionary.update_id
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.update_time
     *
     * @return the value of dictionary.update_time
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.update_time
     *
     * @param updateTime the value for dictionary.update_time
     *
     * @mbg.generated Mon Feb 26 12:00:53 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}