package com.odm.oa.entity;

import java.util.Date;

public class File {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file.file_name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String fileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file.file_url
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String fileUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file.notice_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long noticeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Boolean delFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file.id
	 * @return  the value of file.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file.id
	 * @param id  the value for file.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file.file_name
	 * @return  the value of file.file_name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file.file_name
	 * @param fileName  the value for file.file_name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName == null ? null : fileName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file.file_url
	 * @return  the value of file.file_url
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getFileUrl() {
		return fileUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file.file_url
	 * @param fileUrl  the value for file.file_url
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl == null ? null : fileUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file.notice_id
	 * @return  the value of file.notice_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getNoticeId() {
		return noticeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file.notice_id
	 * @param noticeId  the value for file.notice_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setNoticeId(Long noticeId) {
		this.noticeId = noticeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file.del_flg
	 * @return  the value of file.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Boolean getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file.del_flg
	 * @param delFlg  the value for file.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setDelFlg(Boolean delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file.version
	 * @return  the value of file.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file.version
	 * @param version  the value for file.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file.create_id
	 * @return  the value of file.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file.create_id
	 * @param createId  the value for file.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file.create_time
	 * @return  the value of file.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file.create_time
	 * @param createTime  the value for file.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file.update_id
	 * @return  the value of file.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file.update_id
	 * @param updateId  the value for file.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file.update_time
	 * @return  the value of file.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file.update_time
	 * @param updateTime  the value for file.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}