package com.odm.oa.entity;

import java.util.Date;

public class IllegalWord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_word.id
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_word.word
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_word.del_flg
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    private Boolean delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_word.version
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_word.create_id
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_word.create_time
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_word.update_id
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_word.update_time
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_word.id
     *
     * @return the value of illegal_word.id
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_word.id
     *
     * @param id the value for illegal_word.id
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_word.word
     *
     * @return the value of illegal_word.word
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_word.word
     *
     * @param word the value for illegal_word.word
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_word.del_flg
     *
     * @return the value of illegal_word.del_flg
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_word.del_flg
     *
     * @param delFlg the value for illegal_word.del_flg
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_word.version
     *
     * @return the value of illegal_word.version
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_word.version
     *
     * @param version the value for illegal_word.version
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_word.create_id
     *
     * @return the value of illegal_word.create_id
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_word.create_id
     *
     * @param createId the value for illegal_word.create_id
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_word.create_time
     *
     * @return the value of illegal_word.create_time
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_word.create_time
     *
     * @param createTime the value for illegal_word.create_time
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_word.update_id
     *
     * @return the value of illegal_word.update_id
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_word.update_id
     *
     * @param updateId the value for illegal_word.update_id
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_word.update_time
     *
     * @return the value of illegal_word.update_time
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_word.update_time
     *
     * @param updateTime the value for illegal_word.update_time
     *
     * @mbg.generated Wed Mar 28 18:14:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}