package com.odm.oa.entity;

import java.util.Date;

public class Leaves {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.PERSON_ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String personId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.START_DATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.END_DATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.MINS
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Long mins;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.TYPE_ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Long typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.REASON
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.del_flg
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Boolean delFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.version
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.create_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.create_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.update_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leaves.update_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.ID
	 * @return  the value of leaves.ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.ID
	 * @param id  the value for leaves.ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.PERSON_ID
	 * @return  the value of leaves.PERSON_ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getPersonId() {
		return personId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.PERSON_ID
	 * @param personId  the value for leaves.PERSON_ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setPersonId(String personId) {
		this.personId = personId == null ? null : personId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.START_DATE
	 * @return  the value of leaves.START_DATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.START_DATE
	 * @param startDate  the value for leaves.START_DATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.END_DATE
	 * @return  the value of leaves.END_DATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.END_DATE
	 * @param endDate  the value for leaves.END_DATE
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.MINS
	 * @return  the value of leaves.MINS
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Long getMins() {
		return mins;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.MINS
	 * @param mins  the value for leaves.MINS
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setMins(Long mins) {
		this.mins = mins;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.TYPE_ID
	 * @return  the value of leaves.TYPE_ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Long getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.TYPE_ID
	 * @param typeId  the value for leaves.TYPE_ID
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.REASON
	 * @return  the value of leaves.REASON
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.REASON
	 * @param reason  the value for leaves.REASON
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setReason(String reason) {
		this.reason = reason == null ? null : reason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.del_flg
	 * @return  the value of leaves.del_flg
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Boolean getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.del_flg
	 * @param delFlg  the value for leaves.del_flg
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setDelFlg(Boolean delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.version
	 * @return  the value of leaves.version
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.version
	 * @param version  the value for leaves.version
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.create_id
	 * @return  the value of leaves.create_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.create_id
	 * @param createId  the value for leaves.create_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.create_time
	 * @return  the value of leaves.create_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.create_time
	 * @param createTime  the value for leaves.create_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.update_id
	 * @return  the value of leaves.update_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.update_id
	 * @param updateId  the value for leaves.update_id
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leaves.update_time
	 * @return  the value of leaves.update_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leaves.update_time
	 * @param updateTime  the value for leaves.update_time
	 * @mbg.generated  Wed Feb 28 15:02:56 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}