package com.odm.oa.entity;

import java.util.Date;

public class LegalHoliday {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column legal_holiday.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column legal_holiday.DATE
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column legal_holiday.NAME
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column legal_holiday.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Boolean delFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column legal_holiday.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column legal_holiday.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column legal_holiday.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column legal_holiday.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column legal_holiday.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column legal_holiday.id
	 * @return  the value of legal_holiday.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column legal_holiday.id
	 * @param id  the value for legal_holiday.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column legal_holiday.DATE
	 * @return  the value of legal_holiday.DATE
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column legal_holiday.DATE
	 * @param date  the value for legal_holiday.DATE
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column legal_holiday.NAME
	 * @return  the value of legal_holiday.NAME
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column legal_holiday.NAME
	 * @param name  the value for legal_holiday.NAME
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column legal_holiday.del_flg
	 * @return  the value of legal_holiday.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Boolean getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column legal_holiday.del_flg
	 * @param delFlg  the value for legal_holiday.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setDelFlg(Boolean delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column legal_holiday.version
	 * @return  the value of legal_holiday.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column legal_holiday.version
	 * @param version  the value for legal_holiday.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column legal_holiday.create_id
	 * @return  the value of legal_holiday.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column legal_holiday.create_id
	 * @param createId  the value for legal_holiday.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column legal_holiday.create_time
	 * @return  the value of legal_holiday.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column legal_holiday.create_time
	 * @param createTime  the value for legal_holiday.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column legal_holiday.update_id
	 * @return  the value of legal_holiday.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column legal_holiday.update_id
	 * @param updateId  the value for legal_holiday.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column legal_holiday.update_time
	 * @return  the value of legal_holiday.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column legal_holiday.update_time
	 * @param updateTime  the value for legal_holiday.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}