package com.odm.oa.entity;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.title
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private Long sendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.receive_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private Long receiveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.read_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private String readFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_del_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private Boolean sendDelFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.receive_del_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private Boolean receiveDelFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.del_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private Boolean delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.version
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.update_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.update_time
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.title
     *
     * @return the value of message.title
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.title
     *
     * @param title the value for message.title
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message
     *
     * @return the value of message.message
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message
     *
     * @param message the value for message.message
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_id
     *
     * @return the value of message.send_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public Long getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_id
     *
     * @param sendId the value for message.send_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setSendId(Long sendId) {
        this.sendId = sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.receive_id
     *
     * @return the value of message.receive_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public Long getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.receive_id
     *
     * @param receiveId the value for message.receive_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setReceiveId(Long receiveId) {
        this.receiveId = receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.read_flg
     *
     * @return the value of message.read_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public String getReadFlg() {
        return readFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.read_flg
     *
     * @param readFlg the value for message.read_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setReadFlg(String readFlg) {
        this.readFlg = readFlg == null ? null : readFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_del_flg
     *
     * @return the value of message.send_del_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public Boolean getSendDelFlg() {
        return sendDelFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_del_flg
     *
     * @param sendDelFlg the value for message.send_del_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setSendDelFlg(Boolean sendDelFlg) {
        this.sendDelFlg = sendDelFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.receive_del_flg
     *
     * @return the value of message.receive_del_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public Boolean getReceiveDelFlg() {
        return receiveDelFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.receive_del_flg
     *
     * @param receiveDelFlg the value for message.receive_del_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setReceiveDelFlg(Boolean receiveDelFlg) {
        this.receiveDelFlg = receiveDelFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.del_flg
     *
     * @return the value of message.del_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.del_flg
     *
     * @param delFlg the value for message.del_flg
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.version
     *
     * @return the value of message.version
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.version
     *
     * @param version the value for message.version
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_id
     *
     * @return the value of message.create_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_id
     *
     * @param createId the value for message.create_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.update_id
     *
     * @return the value of message.update_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.update_id
     *
     * @param updateId the value for message.update_id
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.update_time
     *
     * @return the value of message.update_time
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.update_time
     *
     * @param updateTime the value for message.update_time
     *
     * @mbg.generated Thu Mar 29 09:43:15 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}