package com.odm.oa.entity;

import java.util.Date;

public class Module {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.module_name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String moduleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.module_url
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String moduleUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.is_menu
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String isMenu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.parent_menu_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long parentMenuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.module_order
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Integer moduleOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.module_icon
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String moduleIcon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Boolean delFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.id
	 * @return  the value of module.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.id
	 * @param id  the value for module.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.module_name
	 * @return  the value of module.module_name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getModuleName() {
		return moduleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.module_name
	 * @param moduleName  the value for module.module_name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setModuleName(String moduleName) {
		this.moduleName = moduleName == null ? null : moduleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.module_url
	 * @return  the value of module.module_url
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getModuleUrl() {
		return moduleUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.module_url
	 * @param moduleUrl  the value for module.module_url
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setModuleUrl(String moduleUrl) {
		this.moduleUrl = moduleUrl == null ? null : moduleUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.is_menu
	 * @return  the value of module.is_menu
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getIsMenu() {
		return isMenu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.is_menu
	 * @param isMenu  the value for module.is_menu
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setIsMenu(String isMenu) {
		this.isMenu = isMenu == null ? null : isMenu.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.parent_menu_id
	 * @return  the value of module.parent_menu_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getParentMenuId() {
		return parentMenuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.parent_menu_id
	 * @param parentMenuId  the value for module.parent_menu_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setParentMenuId(Long parentMenuId) {
		this.parentMenuId = parentMenuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.module_order
	 * @return  the value of module.module_order
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Integer getModuleOrder() {
		return moduleOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.module_order
	 * @param moduleOrder  the value for module.module_order
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setModuleOrder(Integer moduleOrder) {
		this.moduleOrder = moduleOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.module_icon
	 * @return  the value of module.module_icon
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getModuleIcon() {
		return moduleIcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.module_icon
	 * @param moduleIcon  the value for module.module_icon
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setModuleIcon(String moduleIcon) {
		this.moduleIcon = moduleIcon == null ? null : moduleIcon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.del_flg
	 * @return  the value of module.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Boolean getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.del_flg
	 * @param delFlg  the value for module.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setDelFlg(Boolean delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.version
	 * @return  the value of module.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.version
	 * @param version  the value for module.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.create_id
	 * @return  the value of module.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.create_id
	 * @param createId  the value for module.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.create_time
	 * @return  the value of module.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.create_time
	 * @param createTime  the value for module.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.update_id
	 * @return  the value of module.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.update_id
	 * @param updateId  the value for module.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module.update_time
	 * @return  the value of module.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module.update_time
	 * @param updateTime  the value for module.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}