package com.odm.oa.entity;

import java.util.Date;

public class ModuleRight {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module_right.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module_right.role_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module_right.module_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long moduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module_right.right_kbn
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String rightKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module_right.right_detail
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String rightDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module_right.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Boolean delFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module_right.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module_right.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module_right.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module_right.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column module_right.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module_right.id
	 * @return  the value of module_right.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module_right.id
	 * @param id  the value for module_right.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module_right.role_id
	 * @return  the value of module_right.role_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module_right.role_id
	 * @param roleId  the value for module_right.role_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module_right.module_id
	 * @return  the value of module_right.module_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getModuleId() {
		return moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module_right.module_id
	 * @param moduleId  the value for module_right.module_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setModuleId(Long moduleId) {
		this.moduleId = moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module_right.right_kbn
	 * @return  the value of module_right.right_kbn
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getRightKbn() {
		return rightKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module_right.right_kbn
	 * @param rightKbn  the value for module_right.right_kbn
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setRightKbn(String rightKbn) {
		this.rightKbn = rightKbn == null ? null : rightKbn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module_right.right_detail
	 * @return  the value of module_right.right_detail
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getRightDetail() {
		return rightDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module_right.right_detail
	 * @param rightDetail  the value for module_right.right_detail
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setRightDetail(String rightDetail) {
		this.rightDetail = rightDetail == null ? null : rightDetail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module_right.del_flg
	 * @return  the value of module_right.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Boolean getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module_right.del_flg
	 * @param delFlg  the value for module_right.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setDelFlg(Boolean delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module_right.version
	 * @return  the value of module_right.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module_right.version
	 * @param version  the value for module_right.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module_right.create_id
	 * @return  the value of module_right.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module_right.create_id
	 * @param createId  the value for module_right.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module_right.create_time
	 * @return  the value of module_right.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module_right.create_time
	 * @param createTime  the value for module_right.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module_right.update_id
	 * @return  the value of module_right.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module_right.update_id
	 * @param updateId  the value for module_right.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column module_right.update_time
	 * @return  the value of module_right.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column module_right.update_time
	 * @param updateTime  the value for module_right.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}