package com.odm.oa.entity;

import java.util.Date;

public class NoticeRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_record.id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_record.notice_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Long noticeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_record.user_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_record.read_status
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Boolean readStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_record.del_flg
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Boolean delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_record.version
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_record.create_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_record.create_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_record.update_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_record.update_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_record.read_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Date readTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_record.id
     *
     * @return the value of notice_record.id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_record.id
     *
     * @param id the value for notice_record.id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_record.notice_id
     *
     * @return the value of notice_record.notice_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Long getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_record.notice_id
     *
     * @param noticeId the value for notice_record.notice_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setNoticeId(Long noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_record.user_id
     *
     * @return the value of notice_record.user_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_record.user_id
     *
     * @param userId the value for notice_record.user_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_record.read_status
     *
     * @return the value of notice_record.read_status
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Boolean getReadStatus() {
        return readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_record.read_status
     *
     * @param readStatus the value for notice_record.read_status
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setReadStatus(Boolean readStatus) {
        this.readStatus = readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_record.del_flg
     *
     * @return the value of notice_record.del_flg
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_record.del_flg
     *
     * @param delFlg the value for notice_record.del_flg
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_record.version
     *
     * @return the value of notice_record.version
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_record.version
     *
     * @param version the value for notice_record.version
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_record.create_id
     *
     * @return the value of notice_record.create_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_record.create_id
     *
     * @param createId the value for notice_record.create_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_record.create_time
     *
     * @return the value of notice_record.create_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_record.create_time
     *
     * @param createTime the value for notice_record.create_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_record.update_id
     *
     * @return the value of notice_record.update_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_record.update_id
     *
     * @param updateId the value for notice_record.update_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_record.update_time
     *
     * @return the value of notice_record.update_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_record.update_time
     *
     * @param updateTime the value for notice_record.update_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_record.read_time
     *
     * @return the value of notice_record.read_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_record.read_time
     *
     * @param readTime the value for notice_record.read_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }
}