package com.odm.oa.entity;

import java.util.Date;

public class NoticeResponse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_response.id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_response.response_to_id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    private Long responseToId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_response.del_flg
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_response.version
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_response.create_id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_response.create_time
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_response.update_id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    private String updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_response.update_time
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_response.content
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_response.id
     *
     * @return the value of notice_response.id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_response.id
     *
     * @param id the value for notice_response.id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_response.response_to_id
     *
     * @return the value of notice_response.response_to_id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public Long getResponseToId() {
        return responseToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_response.response_to_id
     *
     * @param responseToId the value for notice_response.response_to_id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public void setResponseToId(Long responseToId) {
        this.responseToId = responseToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_response.del_flg
     *
     * @return the value of notice_response.del_flg
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_response.del_flg
     *
     * @param delFlg the value for notice_response.del_flg
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_response.version
     *
     * @return the value of notice_response.version
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_response.version
     *
     * @param version the value for notice_response.version
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_response.create_id
     *
     * @return the value of notice_response.create_id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_response.create_id
     *
     * @param createId the value for notice_response.create_id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_response.create_time
     *
     * @return the value of notice_response.create_time
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_response.create_time
     *
     * @param createTime the value for notice_response.create_time
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_response.update_id
     *
     * @return the value of notice_response.update_id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_response.update_id
     *
     * @param updateId the value for notice_response.update_id
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_response.update_time
     *
     * @return the value of notice_response.update_time
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_response.update_time
     *
     * @param updateTime the value for notice_response.update_time
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_response.content
     *
     * @return the value of notice_response.content
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_response.content
     *
     * @param content the value for notice_response.content
     *
     * @mbggenerated Mon Feb 12 15:37:41 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}