package com.odm.oa.entity;

import java.util.Date;

public class NoticeType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_type.id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_type.name
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_type.del_flg
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Boolean delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_type.version
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_type.create_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_type.create_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_type.update_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_type.update_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_type.id
     *
     * @return the value of notice_type.id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_type.id
     *
     * @param id the value for notice_type.id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_type.name
     *
     * @return the value of notice_type.name
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_type.name
     *
     * @param name the value for notice_type.name
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_type.del_flg
     *
     * @return the value of notice_type.del_flg
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_type.del_flg
     *
     * @param delFlg the value for notice_type.del_flg
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_type.version
     *
     * @return the value of notice_type.version
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_type.version
     *
     * @param version the value for notice_type.version
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_type.create_id
     *
     * @return the value of notice_type.create_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_type.create_id
     *
     * @param createId the value for notice_type.create_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_type.create_time
     *
     * @return the value of notice_type.create_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_type.create_time
     *
     * @param createTime the value for notice_type.create_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_type.update_id
     *
     * @return the value of notice_type.update_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_type.update_id
     *
     * @param updateId the value for notice_type.update_id
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_type.update_time
     *
     * @return the value of notice_type.update_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_type.update_time
     *
     * @param updateTime the value for notice_type.update_time
     *
     * @mbg.generated Tue Apr 10 09:19:26 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}