package com.odm.oa.entity;

import java.util.Date;

public class Position {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.id
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_name
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.rank
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.remark
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.del_flg
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    private Boolean delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.version
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.create_id
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.create_time
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.update_id
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.update_time
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.id
     *
     * @return the value of position.id
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.id
     *
     * @param id the value for position.id
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_name
     *
     * @return the value of position.position_name
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_name
     *
     * @param positionName the value for position.position_name
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.rank
     *
     * @return the value of position.rank
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.rank
     *
     * @param rank the value for position.rank
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.remark
     *
     * @return the value of position.remark
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.remark
     *
     * @param remark the value for position.remark
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.del_flg
     *
     * @return the value of position.del_flg
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.del_flg
     *
     * @param delFlg the value for position.del_flg
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.version
     *
     * @return the value of position.version
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.version
     *
     * @param version the value for position.version
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.create_id
     *
     * @return the value of position.create_id
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.create_id
     *
     * @param createId the value for position.create_id
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.create_time
     *
     * @return the value of position.create_time
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.create_time
     *
     * @param createTime the value for position.create_time
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.update_id
     *
     * @return the value of position.update_id
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.update_id
     *
     * @param updateId the value for position.update_id
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.update_time
     *
     * @return the value of position.update_time
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.update_time
     *
     * @param updateTime the value for position.update_time
     *
     * @mbg.generated Mon Apr 09 17:59:38 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}