package com.odm.oa.entity;

import java.util.Date;

public class Project {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.manager_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.assistant_manager_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long assistantManagerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.remark
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Boolean delFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.id
	 * @return  the value of project.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.id
	 * @param id  the value for project.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.name
	 * @return  the value of project.name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.name
	 * @param name  the value for project.name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.manager_id
	 * @return  the value of project.manager_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.manager_id
	 * @param managerId  the value for project.manager_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setManagerId(Long managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.assistant_manager_id
	 * @return  the value of project.assistant_manager_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getAssistantManagerId() {
		return assistantManagerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.assistant_manager_id
	 * @param assistantManagerId  the value for project.assistant_manager_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setAssistantManagerId(Long assistantManagerId) {
		this.assistantManagerId = assistantManagerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.remark
	 * @return  the value of project.remark
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.remark
	 * @param remark  the value for project.remark
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.del_flg
	 * @return  the value of project.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Boolean getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.del_flg
	 * @param delFlg  the value for project.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setDelFlg(Boolean delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.version
	 * @return  the value of project.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.version
	 * @param version  the value for project.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.create_id
	 * @return  the value of project.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.create_id
	 * @param createId  the value for project.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.create_time
	 * @return  the value of project.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.create_time
	 * @param createTime  the value for project.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.update_id
	 * @return  the value of project.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.update_id
	 * @param updateId  the value for project.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.update_time
	 * @return  the value of project.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.update_time
	 * @param updateTime  the value for project.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}