package com.odm.oa.entity;

import java.util.Date;

public class Staff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.department_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Long departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_no
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String staffNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.name
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.position_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Long positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.mobile_phone
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.password
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.entry_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Date entryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.graduation_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Date graduationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.graduation_school
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String graduationSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.education
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.subject
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.begin_development_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Date beginDevelopmentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.email
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.sex
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.province_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Long provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.city_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Long cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.district_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Long districtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.address
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.identity_card
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String identityCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.check_status
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String checkStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.status
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.update_password_flg
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String updatePasswordFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.remark
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.del_flg
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Boolean delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.version
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.create_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.create_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.update_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.update_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.id
     *
     * @return the value of staff.id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.id
     *
     * @param id the value for staff.id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.department_id
     *
     * @return the value of staff.department_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.department_id
     *
     * @param departmentId the value for staff.department_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_no
     *
     * @return the value of staff.staff_no
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getStaffNo() {
        return staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_no
     *
     * @param staffNo the value for staff.staff_no
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo == null ? null : staffNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.name
     *
     * @return the value of staff.name
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.name
     *
     * @param name the value for staff.name
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.position_id
     *
     * @return the value of staff.position_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Long getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.position_id
     *
     * @param positionId the value for staff.position_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setPositionId(Long positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.mobile_phone
     *
     * @return the value of staff.mobile_phone
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.mobile_phone
     *
     * @param mobilePhone the value for staff.mobile_phone
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.password
     *
     * @return the value of staff.password
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.password
     *
     * @param password the value for staff.password
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.entry_time
     *
     * @return the value of staff.entry_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.entry_time
     *
     * @param entryTime the value for staff.entry_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.graduation_time
     *
     * @return the value of staff.graduation_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Date getGraduationTime() {
        return graduationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.graduation_time
     *
     * @param graduationTime the value for staff.graduation_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setGraduationTime(Date graduationTime) {
        this.graduationTime = graduationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.graduation_school
     *
     * @return the value of staff.graduation_school
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getGraduationSchool() {
        return graduationSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.graduation_school
     *
     * @param graduationSchool the value for staff.graduation_school
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setGraduationSchool(String graduationSchool) {
        this.graduationSchool = graduationSchool == null ? null : graduationSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.education
     *
     * @return the value of staff.education
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.education
     *
     * @param education the value for staff.education
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.subject
     *
     * @return the value of staff.subject
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.subject
     *
     * @param subject the value for staff.subject
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.begin_development_time
     *
     * @return the value of staff.begin_development_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Date getBeginDevelopmentTime() {
        return beginDevelopmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.begin_development_time
     *
     * @param beginDevelopmentTime the value for staff.begin_development_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setBeginDevelopmentTime(Date beginDevelopmentTime) {
        this.beginDevelopmentTime = beginDevelopmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.email
     *
     * @return the value of staff.email
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.email
     *
     * @param email the value for staff.email
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.sex
     *
     * @return the value of staff.sex
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.sex
     *
     * @param sex the value for staff.sex
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.province_id
     *
     * @return the value of staff.province_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.province_id
     *
     * @param provinceId the value for staff.province_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.city_id
     *
     * @return the value of staff.city_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.city_id
     *
     * @param cityId the value for staff.city_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.district_id
     *
     * @return the value of staff.district_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Long getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.district_id
     *
     * @param districtId the value for staff.district_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setDistrictId(Long districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.address
     *
     * @return the value of staff.address
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.address
     *
     * @param address the value for staff.address
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.identity_card
     *
     * @return the value of staff.identity_card
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.identity_card
     *
     * @param identityCard the value for staff.identity_card
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.check_status
     *
     * @return the value of staff.check_status
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.check_status
     *
     * @param checkStatus the value for staff.check_status
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus == null ? null : checkStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.status
     *
     * @return the value of staff.status
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.status
     *
     * @param status the value for staff.status
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.update_password_flg
     *
     * @return the value of staff.update_password_flg
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getUpdatePasswordFlg() {
        return updatePasswordFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.update_password_flg
     *
     * @param updatePasswordFlg the value for staff.update_password_flg
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setUpdatePasswordFlg(String updatePasswordFlg) {
        this.updatePasswordFlg = updatePasswordFlg == null ? null : updatePasswordFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.remark
     *
     * @return the value of staff.remark
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.remark
     *
     * @param remark the value for staff.remark
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.del_flg
     *
     * @return the value of staff.del_flg
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.del_flg
     *
     * @param delFlg the value for staff.del_flg
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.version
     *
     * @return the value of staff.version
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.version
     *
     * @param version the value for staff.version
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.create_id
     *
     * @return the value of staff.create_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.create_id
     *
     * @param createId the value for staff.create_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.create_time
     *
     * @return the value of staff.create_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.create_time
     *
     * @param createTime the value for staff.create_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.update_id
     *
     * @return the value of staff.update_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.update_id
     *
     * @param updateId the value for staff.update_id
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.update_time
     *
     * @return the value of staff.update_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.update_time
     *
     * @param updateTime the value for staff.update_time
     *
     * @mbg.generated Fri Mar 23 10:40:12 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}