package com.odm.oa.entity;

import java.util.Date;

public class SystemAccountOperationLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_account_operation_log.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_account_operation_log.user_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_account_operation_log.user_name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_account_operation_log.operate_content
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String operateContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_account_operation_log.operate_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date operateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_account_operation_log.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Boolean delFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_account_operation_log.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_account_operation_log.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_account_operation_log.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_account_operation_log.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_account_operation_log.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_account_operation_log.id
	 * @return  the value of system_account_operation_log.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_account_operation_log.id
	 * @param id  the value for system_account_operation_log.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_account_operation_log.user_id
	 * @return  the value of system_account_operation_log.user_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_account_operation_log.user_id
	 * @param userId  the value for system_account_operation_log.user_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_account_operation_log.user_name
	 * @return  the value of system_account_operation_log.user_name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_account_operation_log.user_name
	 * @param userName  the value for system_account_operation_log.user_name
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_account_operation_log.operate_content
	 * @return  the value of system_account_operation_log.operate_content
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getOperateContent() {
		return operateContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_account_operation_log.operate_content
	 * @param operateContent  the value for system_account_operation_log.operate_content
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setOperateContent(String operateContent) {
		this.operateContent = operateContent == null ? null : operateContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_account_operation_log.operate_time
	 * @return  the value of system_account_operation_log.operate_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getOperateTime() {
		return operateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_account_operation_log.operate_time
	 * @param operateTime  the value for system_account_operation_log.operate_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_account_operation_log.del_flg
	 * @return  the value of system_account_operation_log.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Boolean getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_account_operation_log.del_flg
	 * @param delFlg  the value for system_account_operation_log.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setDelFlg(Boolean delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_account_operation_log.version
	 * @return  the value of system_account_operation_log.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_account_operation_log.version
	 * @param version  the value for system_account_operation_log.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_account_operation_log.create_id
	 * @return  the value of system_account_operation_log.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_account_operation_log.create_id
	 * @param createId  the value for system_account_operation_log.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_account_operation_log.create_time
	 * @return  the value of system_account_operation_log.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_account_operation_log.create_time
	 * @param createTime  the value for system_account_operation_log.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_account_operation_log.update_id
	 * @return  the value of system_account_operation_log.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_account_operation_log.update_id
	 * @param updateId  the value for system_account_operation_log.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_account_operation_log.update_time
	 * @return  the value of system_account_operation_log.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_account_operation_log.update_time
	 * @param updateTime  the value for system_account_operation_log.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}