package com.odm.oa.entity;

import java.util.Date;

public class SystemUserRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_user_role.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_user_role.system_account_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long systemAccountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_user_role.role_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_user_role.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Boolean delFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_user_role.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_user_role.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_user_role.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_user_role.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_user_role.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_user_role.id
	 * @return  the value of system_user_role.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_user_role.id
	 * @param id  the value for system_user_role.id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_user_role.system_account_id
	 * @return  the value of system_user_role.system_account_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getSystemAccountId() {
		return systemAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_user_role.system_account_id
	 * @param systemAccountId  the value for system_user_role.system_account_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setSystemAccountId(Long systemAccountId) {
		this.systemAccountId = systemAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_user_role.role_id
	 * @return  the value of system_user_role.role_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_user_role.role_id
	 * @param roleId  the value for system_user_role.role_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_user_role.del_flg
	 * @return  the value of system_user_role.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Boolean getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_user_role.del_flg
	 * @param delFlg  the value for system_user_role.del_flg
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setDelFlg(Boolean delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_user_role.version
	 * @return  the value of system_user_role.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_user_role.version
	 * @param version  the value for system_user_role.version
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_user_role.create_id
	 * @return  the value of system_user_role.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_user_role.create_id
	 * @param createId  the value for system_user_role.create_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_user_role.create_time
	 * @return  the value of system_user_role.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_user_role.create_time
	 * @param createTime  the value for system_user_role.create_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_user_role.update_id
	 * @return  the value of system_user_role.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_user_role.update_id
	 * @param updateId  the value for system_user_role.update_id
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_user_role.update_time
	 * @return  the value of system_user_role.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_user_role.update_time
	 * @param updateTime  the value for system_user_role.update_time
	 * @mbggenerated  Mon Feb 12 15:37:41 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}